sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t laszloforgacs/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true laszloforgacs/docker-react npm run test